### ISSUE TITLE
set-output is going to be deprecated in 2023

### ISSUE THREAD

**Issue by greatislander** [johanvanhelden/clover-coverage-check#10]
First of all, thanks for the great workflow! I got a deprecation warning when using it related to this: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I think the change in `helpers/Output` would be fairly minimal and I'd be happy to file a PR if you would be open to that. Thanks in advance.

**Comment by johanvanhelden** [comment]
Great to hear you like the action.

If you would be able to PR the modification, I'd really appreciate it! Thanks!

**Comment by jospape-newdays** [comment]
UP

**Comment by johanvanhelden** [comment]
The fix has been released, thanks @jospapePAQT !

**Comment by pfy-oleksii-storozhylov** [comment]
No warnings anymore, but I have empty value while trying to access coverage and other values
```
${{ steps.coverage.outputs.coverage }}
```

**Comment by jospape-newdays** [comment]
> No warnings anymore, but I have empty value while trying to access coverage and other values
> 
> ```
> ${{ steps.coverage.outputs.coverage }}
> ```

it is now stored in `$GITHUB_OUTPUT`
```
echo "${{ env.steps.coverage.outputs.coverage }}" # This will output the coverage
```

**Comment by greatislander** [comment]
> > No warnings anymore, but I have empty value while trying to access coverage and other values
> > ```
> > ${{ steps.coverage.outputs.coverage }}
> > ```
> 
> it is now stored in `$GITHUB_OUTPUT`
> 
> ```
> echo "${{ env.steps.coverage.outputs.coverage }}" # This will output the coverage
> ```

The README is not up to date anymore.

**Comment by pfy-oleksii-storozhylov** [comment]
> > No warnings anymore, but I have empty value while trying to access coverage and other values
> > ```
> > ${{ steps.coverage.outputs.coverage }}
> > ```
> 
> it is now stored in `$GITHUB_OUTPUT`
> 
> ```
> echo "${{ env.steps.coverage.outputs.coverage }}" # This will output the coverage
> ```

It doesn't work for me as well :(
Also in docs I found that `env.` should not be used for getting output step value https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-3
But the weird thing they propose to use (and it works for me)
```
echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
```
But in action logs I see output with `##` symbols:
```
##"coverage=99.438202247191" >> $GITHUB_OUTPUT
```

**Comment by johanvanhelden** [comment]
@pfy-oleksii-storozhylov @greatislander @jospapePAQT

Apologies for the late response. Due to personal reasons I was unable to work on this sooner.

I have now pushed the fixes to the action in https://github.com/johanvanhelden/gha-clover-test-coverage-check/pull/13. 

The README on how to use the output remains correct. It was simply a faulty implementation of setting the output in https://github.com/johanvanhelden/gha-clover-test-coverage-check/pull/11/

So any new runs of the workflow should show proper output again, as you can see here:
https://github.com/johanvanhelden/gha-clover-test-coverage-check/actions/runs/3558639385/jobs/5977451791

![image](https://user-images.githubusercontent.com/19389981/204140695-c19b3696-9993-43f3-9d52-0b392b75874c.png)
