### ISSUE TITLE
Empty coverage value

### ISSUE THREAD

**Issue by tobytwigger** [johanvanhelden/clover-coverage-check#12]
Hi!

Since the upgrade to using `$GITHUB_OUTPUT` rather than `set-output`, the outputs from this action have been empty.

At first I thought it may be because of the `##` infront of the `echo "coverage=50%" >> $GITHUB_OUTPUT`, but I changed that and tested it with no luck.

I saw someone else also had this issue, any ideas how to go about fixing this?

        > > No warnings anymore, but I have empty value while trying to access coverage and other values
> > ```
> > ${{ steps.coverage.outputs.coverage }}
> > ```
> 
> it is now stored in `$GITHUB_OUTPUT`
> 
> ```
> echo "${{ env.steps.coverage.outputs.coverage }}" # This will output the coverage
> ```

It doesn't work for me as well :(
Also in docs I found that `env.` should not be used for getting output step value https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-3
But the weird thing they propose to use (and it works for me)
```
echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
```
But in action logs I see output with `##` symbols:
```
##"coverage=99.438202247191" >> $GITHUB_OUTPUT
```

_Originally posted by @pfy-oleksii-storozhylov in https://github.com/johanvanhelden/gha-clover-test-coverage-check/issues/10#issuecomment-1314152111_

**Comment by johanvanhelden** [comment]
Apologies for the late response. Due to personal reasons I was unable to work on this sooner.

I have now pushed the fixes to the action in https://github.com/johanvanhelden/gha-clover-test-coverage-check/pull/13. 

The README on how to use the output remains correct. It was simply a faulty implementation of setting the output in https://github.com/johanvanhelden/gha-clover-test-coverage-check/pull/11/

So any new runs of the workflow should show proper output again, as you can see here:
https://github.com/johanvanhelden/gha-clover-test-coverage-check/actions/runs/3558639385/jobs/5977451791

![image](https://user-images.githubusercontent.com/19389981/204140695-c19b3696-9993-43f3-9d52-0b392b75874c.png)

**Comment by tobytwigger** [comment]
Thanks so much @johanvanhelden, this is now working perfectly for us. Thanks for your time!
